---
- hosts: Debian
  sudo: yes
  gather_facts: true
  tasks: 
    - name: setting up port
      ufw:
        rule: reject
        port: 23
        port: 6005
        port: 8005 
        port: 8080
        port: 8081
    - name:
      ufw:      
        rule: allow
        port: 22
        port: 8080
        port: 8081
        state: reloaded
      



